interface LaundryOwner {
  id: string | number;
  ownerName: string;
  laundryName: string;
  address: string;
  isActivated: boolean;
}

export const allLaundryOwnersList: LaundryOwner[] = [
  {
    id: 1,
    ownerName: 'John Doe',
    laundryName: 'Sparkle Wash',
    address: '123 Main St, NY',
    isActivated: true,
  },
  {
    id: 2,
    ownerName: 'Jane Smith',
    laundryName: 'Fresh Cleaners',
    address: '456 Elm St, LA',
    isActivated: true,
  },
  {
    id: 3,
    ownerName: 'Michael Brown',
    laundryName: 'Quick Wash',
    address: '789 Oak St, TX',
    isActivated: true,
  },
  {
    id: 4,
    ownerName: 'Sarah Johnson',
    laundryName: 'Bright Whites',
    address: '321 Pine St, FL',
    isActivated: false,
  },
  {
    id: 5,
    ownerName: 'David Wilson',
    laundryName: 'Super Suds',
    address: '654 Maple St, IL',
    isActivated: true,
  },
  {
    id: 6,
    ownerName: 'Emily Clark',
    laundryName: 'Perfect Press',
    address: '987 Birch St, WA',
    isActivated: true,
  },
  {
    id: 7,
    ownerName: 'Robert Miller',
    laundryName: 'Wash & Go',
    address: '741 Cedar St, NV',
    isActivated: true,
  },
  {
    id: 8,
    ownerName: 'Sophia White',
    laundryName: 'Neat & Clean',
    address: '852 Willow St, CO',
    isActivated: true,
  },
  {
    id: 9,
    ownerName: 'Daniel Lee',
    laundryName: 'Tidy Laundry',
    address: '159 Redwood St, AZ',
    isActivated: true,
  },
  {
    id: 10,
    ownerName: 'Olivia Martinez',
    laundryName: 'Shiny Suds',
    address: '369 Spruce St, GA',
    isActivated: true,
  },
  {
    id: 11,
    ownerName: 'James Rodriguez',
    laundryName: 'Fresh Press',
    address: '753 Cedar St, CA',
    isActivated: false,
  },
  {
    id: 12,
    ownerName: 'Ava Hernandez',
    laundryName: 'Quick Clean',
    address: '852 Birch St, VA',
    isActivated: true,
  },
  {
    id: 13,
    ownerName: 'Alexander Brown',
    laundryName: 'Bright Whites',
    address: '963 Pine St, TX',
    isActivated: true,
  },
  {
    id: 14,
    ownerName: 'Mia Davis',
    laundryName: 'Super Suds',
    address: '159 Elm St, FL',
    isActivated: true,
  },
  {
    id: 15,
    ownerName: 'William Wilson',
    laundryName: 'Perfect Press',
    address: '357 Oak St, IL',
    isActivated: true,
  },
  {
    id: 16,
    ownerName: 'Sofia Clark',
    laundryName: 'Wash & Go',
    address: '852 Maple St, WA',
    isActivated: true,
  },
  {
    id: 17,
    ownerName: 'Benjamin Miller',
    laundryName: 'Neat & Clean',
    address: '963 Cedar St, NV',
    isActivated: true,
  },
  {
    id: 18,
    ownerName: 'Charlotte White',
    laundryName: 'Tidy Laundry',
    address: '357 Willow St, CO',
    isActivated: true,
  },
  {
    id: 19,
    ownerName: 'Ethan Lee',
    laundryName: 'Shiny Suds',
    address: '852 Redwood St, AZ',
    isActivated: true,
  },
  {
    id: 20,
    ownerName: 'Amelia Martinez',
    laundryName: 'Fresh Press',
    address: '963 Spruce St, GA',
    isActivated: false,
  },
  {
    id: 21,
    ownerName: 'Michael Rodriguez',
    laundryName: 'Quick Clean',
    address: '357 Cedar St, CA',
    isActivated: true,
  },
  {
    id: 22,
    ownerName: 'Sophia Hernandez',
    laundryName: 'Bright Whites',
    address: '852 Birch St, VA',
    isActivated: true,
  },
  {
    id: 23,
    ownerName: 'Daniel Brown',
    laundryName: 'Super Suds',
    address: '963 Pine St, TX',
    isActivated: true,
  },
  {
    id: 24,
    ownerName: 'Olivia Davis',
    laundryName: 'Perfect Press',
    address: '159 Elm St, FL',
    isActivated: true,
  },
  {
    id: 25,
    ownerName: 'James Wilson',
    laundryName: 'Wash & Go',
    address: '357 Oak St, IL',
    isActivated: true,
  },
  {
    id: 26,
    ownerName: 'Ava Clark',
    laundryName: 'Neat & Clean',
    address: '852 Maple St, WA',
    isActivated: true,
  },
  {
    id: 27,
    ownerName: 'Alexander Miller',
    laundryName: 'Tidy Laundry',
    address: '963 Cedar St, NV',
    isActivated: true,
  },
  {
    id: 28,
    ownerName: 'Mia White',
    laundryName: 'Shiny Suds',
    address: '357 Willow St, CO',
    isActivated: true,
  },
  {
    id: 29,
    ownerName: 'William Lee',
    laundryName: 'Fresh Press',
    address: '852 Redwood St, AZ',
    isActivated: true,
  },
  {
    id: 30,
    ownerName: 'Sofia Martinez',
    laundryName: 'Quick Clean',
    address: '963 Spruce St, GA',
    isActivated: true,
  },
  {
    id: 31,
    ownerName: 'Benjamin Rodriguez',
    laundryName: 'Bright Whites',
    address: '357 Cedar St, CA',
    isActivated: true,
  },
  {
    id: 32,
    ownerName: 'Charlotte Hernandez',
    laundryName: 'Super Suds',
    address: '852 Birch St, VA',
    isActivated: true,
  },
  {
    id: 33,
    ownerName: 'Ethan Brown',
    laundryName: 'Perfect Press',
    address: '963 Pine St, TX',
    isActivated: true,
  },
  {
    id: 34,
    ownerName: 'Amelia Davis',
    laundryName: 'Wash & Go',
    address: '159 Elm St, FL',
    isActivated: true,
  },
  {
    id: 35,
    ownerName: 'Michael Wilson',
    laundryName: 'Neat & Clean',
    address: '357 Oak St, IL',
    isActivated: true,
  },
  {
    id: 36,
    ownerName: 'Sophia Clark',
    laundryName: 'Tidy Laundry',
    address: '852 Maple St, WA',
    isActivated: true,
  },
  {
    id: 37,
    ownerName: 'Daniel Miller',
    laundryName: 'Shiny Suds',
    address: '963 Cedar St, NV',
    isActivated: true,
  },
];
